FROM emscripten/emsdk:1.39.17

# Debian Buster Repositories auf Archive umstellen
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org|archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    sed -i '/updates/d' /etc/apt/sources.list

RUN apt-get update && apt-get install -y wget build-essential apt-transport-https scons
WORKDIR /app

EXPOSE 8000
